### ISSUE TITLE
pip install neural_renderer_pytorch error: No CUDA runtime is found, using CUDA_HOME='/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/intel2016.4/cuda/8.0.44'

### ISSUE THREAD

**Issue by moldach** [daniilidis-group/neural_renderer#105]
I'm getting an error trying to install into a virtual environment - likely because I'm loading `cuda` as a module on a `HPCC`
```
(venv) [moldach@gra-login1 neural_renderer]$ pip install neural_renderer_pytorch
Ignoring pip: markers 'python_version < "3"' don't match your environment
Collecting neural_renderer_pytorch
  Using cached https://files.pythonhosted.org/packages/15/28/dd59b5098e60e75948ae414ee65700597217199591dffa22797f47914702/neural_renderer_pytorch-1.1.3.tar.gz
Requirement already satisfied: torch in ./venv/lib/python3.6/site-packages (from neural_renderer_pytorch)
Requirement already satisfied: numpy in ./venv/lib/python3.6/site-packages (from neural_renderer_pytorch)
Collecting scikit-image (from neural_renderer_pytorch)
Requirement already satisfied: dataclasses; python_version < "3.7" in ./venv/lib/python3.6/site-packages (from torch->neural_renderer_pytorch)
Requirement already satisfied: typing-extensions in ./venv/lib/python3.6/site-packages (from torch->neural_renderer_pytorch)
Collecting pillow!=7.1.0,!=7.1.1,>=4.3.0 (from scikit-image->neural_renderer_pytorch)
  Downloading https://files.pythonhosted.org/packages/60/f0/dd2eb7911f948bf529f58f0c7931f6f6466f711bd6f1d81a69dc4edd4e2a/Pillow-8.1.2.tar.gz (45.2MB)
    100% |████████████████████████████████| 45.2MB 33kB/s 
Collecting scipy>=1.0.1 (from scikit-image->neural_renderer_pytorch)
Collecting networkx>=2.0 (from scikit-image->neural_renderer_pytorch)
  Cache entry deserialization failed, entry ignored
Collecting matplotlib!=3.0.0,>=2.0.0 (from scikit-image->neural_renderer_pytorch)
  Downloading https://files.pythonhosted.org/packages/22/d4/e7ca532e68a9357742604e1e4ae35d9c09a4a810de39a9d80402bd12f50f/matplotlib-3.3.4.tar.gz (37.9MB)
    100% |████████████████████████████████| 37.9MB 40kB/s 
Collecting PyWavelets>=1.1.1 (from scikit-image->neural_renderer_pytorch)
Collecting imageio>=2.3.0 (from scikit-image->neural_renderer_pytorch)
Collecting tifffile>=2019.7.26 (from scikit-image->neural_renderer_pytorch)
Collecting decorator>=4.3.0 (from networkx>=2.0->scikit-image->neural_renderer_pytorch)
  Cache entry deserialization failed, entry ignored
Collecting cycler>=0.10 (from matplotlib!=3.0.0,>=2.0.0->scikit-image->neural_renderer_pytorch)
Collecting kiwisolver>=1.0.1 (from matplotlib!=3.0.0,>=2.0.0->scikit-image->neural_renderer_pytorch)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 (from matplotlib!=3.0.0,>=2.0.0->scikit-image->neural_renderer_pytorch)
  Cache entry deserialization failed, entry ignored
Collecting python-dateutil>=2.1 (from matplotlib!=3.0.0,>=2.0.0->scikit-image->neural_renderer_pytorch)
  Cache entry deserialization failed, entry ignored
Collecting six (from cycler>=0.10->matplotlib!=3.0.0,>=2.0.0->scikit-image->neural_renderer_pytorch)
  Cache entry deserialization failed, entry ignored
Installing collected packages: pillow, scipy, decorator, networkx, six, cycler, kiwisolver, pyparsing, python-dateutil, matplotlib, PyWavelets, imageio, tifffile, scikit-image, neural-renderer-pytorch
  Running setup.py install for pillow ... done
  Running setup.py install for matplotlib ... done
  Running setup.py install for neural-renderer-pytorch ... error
    Complete output from command /scratch/moldach/neural_renderer/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2v6q8bqq/neural-renderer-pytorch/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7ckyw0sx-record/install-record.txt --single-version-externally-managed --compile --install-headers /scratch/moldach/neural_renderer/venv/include/site/python3.6/neural-renderer-pytorch:
    No CUDA runtime is found, using CUDA_HOME='/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/intel2016.4/cuda/8.0.44'
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/vertices_to_faces.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/save_obj.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/renderer.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/rasterize.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/projection.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/perspective.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/mesh.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/look_at.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/look.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/load_obj.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/lighting.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/get_points_from_angles.py -> build/lib.linux-x86_64-3.6/neural_renderer
    copying neural_renderer/__init__.py -> build/lib.linux-x86_64-3.6/neural_renderer
    creating build/lib.linux-x86_64-3.6/neural_renderer/cuda
    copying neural_renderer/cuda/__init__.py -> build/lib.linux-x86_64-3.6/neural_renderer/cuda
    running build_ext
    building 'neural_renderer.cuda.load_textures' extension
    creating /tmp/pip-build-2v6q8bqq/neural-renderer-pytorch/build/temp.linux-x86_64-3.6
    creating /tmp/pip-build-2v6q8bqq/neural-renderer-pytorch/build/temp.linux-x86_64-3.6/neural_renderer
    creating /tmp/pip-build-2v6q8bqq/neural-renderer-pytorch/build/temp.linux-x86_64-3.6/neural_renderer/cuda
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2v6q8bqq/neural-renderer-pytorch/setup.py", line 40, in <module>
        cmdclass = {'build_ext': BuildExtension}
      File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/scratch/moldach/neural_renderer/venv/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/scratch/moldach/neural_renderer/venv/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/scratch/moldach/neural_renderer/venv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
        build_ext.build_extensions(self)
      File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/scratch/moldach/neural_renderer/venv/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/scratch/moldach/neural_renderer/venv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 524, in unix_wrap_ninja_compile
        cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
      File "/scratch/moldach/neural_renderer/venv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 423, in unix_cuda_flags
        cflags + _get_cuda_arch_flags(cflags))
      File "/scratch/moldach/neural_renderer/venv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1561, in _get_cuda_arch_flags
        arch_list[-1] += '+PTX'
    IndexError: list index out of range
    
    ----------------------------------------
Command "/scratch/moldach/neural_renderer/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2v6q8bqq/neural-renderer-pytorch/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7ckyw0sx-record/install-record.txt --single-version-externally-managed --compile --install-headers /scratch/moldach/neural_renderer/venv/include/site/python3.6/neural-renderer-pytorch" failed with error code 1 in /tmp/pip-build-2v6q8bqq/neural-renderer-pytorch/
```

Any idea how I can provide the proper path for installation?

```
$ pip install --no-index tensorflow_gpu

(venv) [moldach@gra-login1 neural_renderer]$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44
```

## `pip freeze`:

```
(venv) [moldach@gra-login1 neural_renderer]$ pip freeze
-f /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/avx2
-f /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/generic
-f /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
absl-py==0.11.0
astunparse==1.6.3
cachetools==4.2.1
certifi==2020.12.5
chardet==4.0.0
cycler==0.10.0
dataclasses==0.8
decorator==4.4.2
gast==0.3.3
google-auth==1.27.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
grpcio==1.32.0
h5py==2.10.0
idna==2.10
imageio==2.9.0
importlib-metadata==3.7.2
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
Markdown==3.3.4
matplotlib==3.3.4
networkx==2.5
numpy==1.18.4
oauthlib==3.1.0
opt-einsum==3.3.0
Pillow==8.1.2
protobuf==3.15.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
python-dateutil==2.8.1
PyWavelets==1.1.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
scikit-image==0.17.2
scipy==1.4.1
six==1.15.0
tensorboard==2.4.1
tensorboard-plugin-wit==1.7.0
tensorflow-estimator==2.3.0
tensorflow-gpu==2.3.0
termcolor==1.1.0
tifffile==2020.9.3
torch==1.8.0
torchaudio==0.7.2
torchvision==0.8.2
typing-extensions==3.7.4.3
urllib3==1.26.4
Werkzeug==1.0.1
wrapt==1.11.2
zipp==3.4.1
```

**Comment by HuYichun** [comment]
same here

**Comment by huytuong010101** [comment]
same here :((((

**Comment by xk-huang** [comment]
arch_list problem: `export TORCH_CUDA_ARCH_LIST="Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing"`

**Comment by rohit7044** [comment]
Download the repository and run ``` pthon setup.py install ```

**Comment by linjiangya** [comment]
same here
