### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 1)

### ISSUE THREAD

**Issue by Mayur28** [daniilidis-group/neural_renderer#120]
Hi,

I have installed from source and I am trying to run the example, but I am encountering an error when trying to unpack values returned from the renderer:

`ValueError: not enough values to unpack (expected 3, got 1)`

I am trying to get this to work on Windows 10 Pro.

Traceback:
```
Installed c:\users\XXXX\appdata\local\programs\python\python36\lib\site-packages\neural_renderer_pytorch-1.1.3-py3.6-win-amd64.egg
Processing dependencies for neural-renderer-pytorch==1.1.3
Finished processing dependencies for neural-renderer-pytorch==1.1.3


D:\XXXX\Downloads\neural_renderer-master\neural_renderer-master>cd examples

D:\XXXX\Downloads\neural_renderer-master\neural_renderer-master\examples>python example1.py
Drawing:   0%|                                                                                                                                                                               | 0/90 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "example1.py", line 55, in <module>
    main()
  File "example1.py", line 49, in main
    images, _, _ = renderer(vertices, faces, textures)  # [batch_size, RGB, image_size, image_size]
ValueError: not enough values to unpack (expected 3, got 1)
```

Any help would be highly appreciated.
Thanks

**Comment by Azusa306** [comment]
do you solve this problem？
`Traceback (most recent call last):
  File "./examples/example1.py", line 55, in <module>
    main()
  File "./examples/example1.py", line 49, in main
    images, _, _ = renderer(vertices, faces, textures)  # [batch_size, RGB, image_size, image_size]
ValueError: not enough values to unpack (expected 3, got 2)`

**Comment by Mayur28** [comment]
Hi @Azusa306,

I can't remember what exactly I did to resolve the problem as it was a while back, but if I remember correctly, I resolved the issue by building from source, and I had to change a few lines in the code to get it to work. Can't remember the exact details - Apologies.

**Comment by Azusa306** [comment]
Thanks.I have resolved it.
Just delete one '_' after the image.
