### ISSUE TITLE
problem about 'python setup.py install'

### ISSUE THREAD

**Issue by Masterzhuior** [daniilidis-group/neural_renderer#132]
```
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    'neural_renderer/cuda/load_textures_cuda_kernel.cu',
  File "/home/zjj/anaconda3/envs/flow/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 912, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/home/zjj/anaconda3/envs/flow/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1020, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/home/zjj/anaconda3/envs/flow/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 2035, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```

**Comment by kevintsq** [comment]
You need to set the `CUDA_HOME` environment variable to your CUDA installation root.
