### ISSUE TITLE
ImportError: /data/user/anconda3/envs/neural_test/lib/python3.7/site-packages/neural_renderer/cuda/load_textures.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv

### ISSUE THREAD

**Issue by fcyx** [daniilidis-group/neural_renderer#136]
import neural_renderer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/user/anconda3/envs/neural_test/lib/python3.7/site-packages/neural_renderer/__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "/data/user/anconda3/envs/neural_test/lib/python3.7/site-packages/neural_renderer/load_obj.py", line 8, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: /data/user/anconda3/envs/neural_test/lib/python3.7/site-packages/neural_renderer/cuda/load_textures.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv

The installation problem was finally solved, but the above problems occurred in the import. Can anyone help explain?

**Comment by Hao-hui** [comment]
I also encountered the same problem. Under what conditions did you solve it?

**Comment by fcyx** [comment]
> I was the problem was due to version mismatch, so I upgraded CUDA to 11, and so did pytorch. After that, you can install other plugins that correspond to them.

**Comment by Hao-hui** [comment]
> 

![image](https://user-images.githubusercontent.com/82891524/194704911-c1ccc2e5-a3a3-4905-8033-a2e30d7284bf.png)
Thank you for your reply, I upgraded CUDA to 11.1, and deployed torch1.8.0+cu111. But the problem in the picture occurred. Have you seen it ?  (GeForce RTX 3090, Driver Version: 455.23.04, CUDA Version: 11.1)

**Comment by Hao-hui** [comment]
@fcyx Thank you. I have solved the problem. (Deployment: CUDA11.1, torch 1.8.1+cu11.1, GeForce RTX 3090)
