### ISSUE TITLE
unknown setup problem, RTX 3090 + cuda 11.1, already convert AT_CHECK to TROCH_CHECK

### ISSUE THREAD

**Issue by tyq996** [daniilidis-group/neural_renderer#145]
I get a unknown problem when I want to run this command: python3 setup.py install.
building 'neural_renderer.cuda.load_textures' extension
Emitting ninja build file /media/public/新加卷/JMH/model-based/training/neural_renderer-master/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/local/cuda-11.1/bin/nvcc  -I/home/public/anaconda3/lib/python3.7/site-packages/torch/include -I/home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/public/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/public/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.1/include -I/home/public/anaconda3/include/python3.7m -c -c '/media/public/新加卷/JMH/model-ba/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda_kernel.cu' -o '/media/public/新加卷/JMH/model-based/training/neural_renderer-ter/build/temp.linux-x86_64-3.7/neural_renderer/cuda/load_textures_cuda_kernel.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=load_textures -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /media/public/新加卷/JMH/model-based/training/neural_renderer-master/build/temp.linux-x86_64-3.7/neural_renderer/cuda/load_textures_cuda_kerne 
/usr/local/cuda-11.1/bin/nvcc  -I/home/public/anaconda3/lib/python3.7/site-packages/torch/include -I/home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/public/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/public/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.1/include -I/home/public/anaconda3/include/python3.7m -c -c '/media/public/新加卷/JMH/model-based/tring/neural_renderer-master/neural_renderer/cuda/load_textures_cuda_kernel.cu' -o '/media/public/新加卷/JMH/model-based/training/neural_renderer-masterild/temp.linux-x86_64-3.7/neural_renderer/cuda/load_textures_cuda_kernel.o' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=load_textures -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/bin/sh: 1: /usr/local/cuda-11.1/bin/nvcc: not found
[2/2] c++ -MMD -MF '/media/public/新加卷/JMH/model-based/training/neural_renderer-master/build/temp.linux-x86_64-3.7/neural_renderer/cuda/load_textureuda.o'.d -pthread -B /home/public/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/public/anaconda3/lib/python3.7/site-packages/torch/include -I/home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/public/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/home/public/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.1/include -I/home/public/anaconda3/include/python3.7m -c -c '/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neurrenderer/cuda/load_textures_cuda.cpp' -o '/media/public/新加卷/JMH/model-based/training/neural_renderer-master/build/temp.linux-x86_64-3.7/neural_rendr/cuda/load_textures_cuda.o' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=load_textures -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:140:0,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:1:
/home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:87:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 ^
In file included from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/DeviceType.h:8:0,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Device.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:1:
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp: In function ‘at::Tensor load_textures(at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int)’:
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:15:42: warning: ‘at::DeprecatedTypePrrties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                                          ^
/home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/macros/Macros.h:195:64: note: in definition of macro ‘C10_UNLIKELY’
 #define C10_UNLIKELY(expr) (__builtin_expect(static_cast<bool>(expr), 0))
                                                                ^
/home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:430:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {            \
       ^
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:15:23: note: in expansion of macro ‘TH_CHECK’
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:17:24: note: in expansion of macro ‘CK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:28:5: note: in expansion of macro ‘CH_INPUT’
     CHECK_INPUT(image);
     ^
In file included from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:1:
/home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:338:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^
In file included from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/DeviceType.h:8:0,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Device.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:1:
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:15:42: warning: ‘at::DeprecatedTypePrrties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                                          ^
/home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/macros/Macros.h:195:64: note: in definition of macro ‘C10_UNLIKELY’
 #define C10_UNLIKELY(expr) (__builtin_expect(static_cast<bool>(expr), 0))
                                                                ^
/home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:430:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {            \
       ^
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:15:23: note: in expansion of macro ‘TH_CHECK’
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:17:24: note: in expansion of macro ‘CK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:29:5: note: in expansion of macro ‘CH_INPUT’
     CHECK_INPUT(faces);
     ^
In file included from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:1:
/home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:338:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^
In file included from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/DeviceType.h:8:0,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Device.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:1:
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:15:42: warning: ‘at::DeprecatedTypePrrties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                                          ^
/home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/macros/Macros.h:195:64: note: in definition of macro ‘C10_UNLIKELY’
 #define C10_UNLIKELY(expr) (__builtin_expect(static_cast<bool>(expr), 0))
                                                                ^
/home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:430:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {            \
       ^
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:15:23: note: in expansion of macro ‘TH_CHECK’
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:17:24: note: in expansion of macro ‘CK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:30:5: note: in expansion of macro ‘CH_INPUT’
     CHECK_INPUT(is_update);
     ^
In file included from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:1:
/home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:338:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^
In file included from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/DeviceType.h:8:0,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Device.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:1:
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:15:42: warning: ‘at::DeprecatedTypePrrties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                                          ^
/home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/macros/Macros.h:195:64: note: in definition of macro ‘C10_UNLIKELY’
 #define C10_UNLIKELY(expr) (__builtin_expect(static_cast<bool>(expr), 0))
                                                                ^
/home/public/anaconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:430:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {            \
       ^
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:15:23: note: in expansion of macro ‘TH_CHECK’
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
                       ^
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:17:24: note: in expansion of macro ‘CK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^
/media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:31:5: note: in expansion of macro ‘CH_INPUT’
     CHECK_INPUT(textures);
     ^
In file included from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/public/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /media/public/新加卷/JMH/model-based/training/neural_renderer-master/neural_renderer/cuda/load_textures_cuda.cpp:1:
/home/public/anaconda3/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:338:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/public/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1672, in _run_ninja_build
    env=env)
  File "/home/public/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    cmdclass = {'build_ext': BuildExtension}
  File "/home/public/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/public/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/public/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/public/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/public/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/public/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/public/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/public/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/public/anaconda3/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/public/anaconda3/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "/home/public/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/public/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/public/anaconda3/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/public/anaconda3/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/public/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/public/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/public/anaconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/public/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/public/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/public/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "/home/public/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/public/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/public/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/public/anaconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/public/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/public/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 539, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/public/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1360, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/public/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension.

What's wrong with my installation? Who can help me?

**Comment by MTzhong** [comment]
/bin/sh: 1: /usr/local/cuda-11.1/bin/nvcc: not found
我也遇到过这个问题，本地环境(不是conda虚拟环境)装了多个cuda版本导致nvcc not found
如果我没猜错 你现在本地环境中的cuda是冲突的

**Comment by MilesTheProwler** [comment]
@tyq996  I got same error like you. How did you solve it ?
