### ISSUE TITLE
ValueError: mode should be one of None, 'silhouettes' or 'depth'

### ISSUE THREAD

**Issue by MilesTheProwler** [daniilidis-group/neural_renderer#146]
Hi can someone help me to solve this error ? I used python 3.6 with pytorch 1.10.0 with cuda 11.3 and pytorch3d 0.4.0 

```
Traceback (most recent call last):
  File "texture_generation.py", line 385, in <module>
    pose_seq='src', img_size=1024, generate_ref=generate_ref)
  File "/home/ubuntu4090/Desktop/HF-Avatar/utils/data_generation.py", line 348, in generate_uv
    self.trans_flow.load_src_vertices_list(src_vertices_list)
  File "/home/ubuntu4090/Desktop/HF-Avatar/utils/data_generation.py", line 184, in load_src_vertices_list
    src_f2verts, src_fim, src_wim = self.renderer(src_vertices, self.faces, mode='fim_and_wim')
  File "/home/ubuntu4090/miniconda3/envs/Avatar/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu4090/miniconda3/envs/Avatar/lib/python3.6/site-packages/neural_renderer_pytorch-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/renderer.py", line 80, in forward
    raise ValueError("mode should be one of None, 'silhouettes' or 'depth'")
ValueError: mode should be one of None, 'silhouettes' or 'depth'
```

**Comment by MilesTheProwler** [comment]
Solve it !
