### ISSUE TITLE
Cannot run example1.py

### ISSUE THREAD

**Issue by monajalal** [daniilidis-group/neural_renderer#93]
```
$ python ./examples/example1.py
Traceback (most recent call last):
  File "./examples/example1.py", line 12, in <module>
    import neural_renderer as nr
  File "/home/mona/anaconda3/lib/python3.7/site-packages/neural_renderer/__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "/home/mona/anaconda3/lib/python3.7/site-packages/neural_renderer/load_obj.py", line 8, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: /home/mona/anaconda3/lib/python3.7/site-packages/neural_renderer/cuda/load_textures.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass
```

**Comment by monajalal** [comment]
https://github.com/daniilidis-group/neural_renderer/issues/94
